### ISSUE TITLE
User can login without admin's intervention (using Re-send confirmation button)

### ISSUE THREAD

**Issue by johnnylupino** [hrimhari/moodle-auth_emailadmin#45] opened 2020-10-05 09:17 UTC
Hi,

The issue is about a newly registered user who attempts to login before being confirmed by admin.
When user enters his credentials given during the registration into the moodle  standard login form then  'Re-send confirmation' button appears to him.
He clicks on the button to re-send confirmation link and he now receives email with confirmation link.
By copy/paste, his registration is now confirmed and he is logged in automatically.
This whole process is carried out without admins intervention.

Please find below steps to reproduce the issue:

1. Click create a new account 
2. Try to connect without waiting for validation by an admin
3. Click on the "Resend the confirmation email" button displayed 
4. Click on the account activation link received in the confirmation email.
5. The user accesses the platform without the admin intervening

*Email-based self-registration is disabled

Plugin version: 1.4.5 (2030061000)
Moodle version: 3.9.2

I hope I have not doubled this issue already...
Kind regards,
Archie

**Comment by hrimhari** [comment] 2020-12-03 02:52
This is a core Moodle functionality added since 3.6: https://tracker.moodle.org/browse/MDL-17943

**Comment by hrimhari** [comment] 2020-12-03 02:53
The logic exists in `auth/classes/external.php`.

**Comment by hrimhari** [comment] 2020-12-03 03:14
I see no way to work around it. I opened a bug with Moodle: https://tracker.moodle.org/browse/MDL-70381

**Comment by hrimhari** [comment] 2020-12-26 02:24
I proposed a fix upstream. Please vote/comment on https://tracker.moodle.org/browse/MDL-70381

**Comment by hrimhari** [comment] 2021-01-31 00:55
I created patches that can be applied with `git patch` while waiting for them to be applied upstream.

To apply:

1. Download ZIP: [moodle-MDL-70381-patches.zip](https://github.com/hrimhari/moodle-auth_emailadmin/files/5899018/moodle-MDL-70381-patches.zip)
2. Expand ZIP to `/tmp`:
```
cd /tmp
unzip path/to/moodle-MDL-70381-patches.zip
```
3. Select correct patch for your Moodle version. If 3.6 or 3.7, use patch ending with `-36.patch` or `-37.patch`. If newer, use the unversioned file.
4. Change directory to where your Moodle is installed, then use `git patch`. For example, if your Moodle is 3.9 and is installed under `/var/www/html/moodle`:
```
cd /var/www/html/moodle
git apply /tmp/moodle-MDL-70381.patch
```
5. If patch applies correctly, no message will be displayed. You can verify it works by registering a new account and attempting to sign in before the account is confirmed. You won't be able to "resend confirmation" if you're using "emailadmin" as Auth Registration, but will be able to if you're using "email".

**Comment by jasimp** [comment] 2021-02-15 08:08
is this patch can work with latest moodle 3.10?

**Comment by hrimhari** [comment] 2021-02-15 13:19
> is this patch can work with latest moodle 3.10?

Yes.

**Comment by amjohnson46** [comment] 2021-02-16 21:35
I can't access the bug tracker issue to vote for it. Is that because they've raised it to a security-level issue which limits visibility?

**Comment by hrimhari** [comment] 2021-02-16 21:43
> I can't access the bug tracker issue to vote for it. Is that because they've raised it to a security-level issue which limits visibility?

I dunno. Did you register to their tracker?

**Comment by amjohnson46** [comment] 2021-02-16 21:54
Yes. I can view other issues, but not the one you linked above.

**Comment by dedsxepto** [comment] 2021-04-07 07:59
Can this not bail out using the pre_user_login_hook instead?  So if unconfirmed, a proper reason can be shown similar to how it's done for suspended users?

**Comment by deds** [comment] 2021-04-08 11:16
> Can this not bail out using the pre_user_login_hook instead? So if unconfirmed, a proper reason can be shown similar to how it's done for suspended users?

I looked into this further and pre_user_login_hook won't work since there's no way to signify exit of the code.  (NOTE: dedsxepto is my work account).  Instead, the user_login method can just handle this on its own.  I created PR #46 for this.

**Comment by jasimp** [comment] 2021-05-10 04:42
with the admin approval plug in there are two issues are there

1. the user not getting any email notification after submitting their profile details
2. Also the user not getting any account validation email to validate their email address as the admin getting the link. so there is chance for spelling error while creating the account and this can cause spam later

**Comment by hrimhari** [comment] 2021-06-08 04:21
@jasimp, this plugin's goal is to have the Admin validate the request, not the user.

**Comment by jasimp** [comment] 2021-06-08 05:49
Thank you Felipe
Sorry for post in a wrong thread
But as a self registration standard and best practice, the user email need to validate ( double opt) always to avoid email issues  in later stage.

**Comment by jasimp** [comment] 2021-07-24 12:27
> I created patches that can be applied with `git patch` while waiting for them to be applied upstream.
> 
> To apply:
> 
> 1. Download ZIP: [moodle-MDL-70381-patches.zip](https://github.com/hrimhari/moodle-auth_emailadmin/files/6613414/moodle-MDL-70381-patches.zip)
> 2. Expand ZIP to `/tmp`:
> 
> ```
> cd /tmp
> unzip path/to/moodle-MDL-70381-patches.zip
> ```
> 
> 1. Select correct patch for your Moodle version. If 3.6, 3.7 or 3.11, use patch ending with `-36.patch`, `-37.patch` or '-311.patch'. Otherwise, use the unversioned file.
> 2. Change directory to where your Moodle is installed, then use `git patch`. For example, if your Moodle is 3.9 and is installed under `/var/www/html/moodle`:
> 
> ```
> cd /var/www/html/moodle
> git apply /tmp/moodle-MDL-70381.patch
> ```
> 
> 1. If patch applies correctly, no message will be displayed. You can verify it works by registering a new account and attempting to sign in before the account is confirmed. You won't be able to "resend confirmation" if you're using "emailadmin" as Auth Registration, but will be able to if you're using "email".
---------------------------------------------------------------------------------------------------------------------------------------
Hi Felipe
Is this bug fixed in any of the future updates? or do we still need the patch while upgrading moodle

**Comment by hrimhari** [comment] 2021-07-24 13:46
It's not fixed yet. The patch is still needed.

**Comment by jasimp** [comment] 2021-07-25 00:06
> It's not fixed yet. The patch is still needed.

Thank you for the updates

**Comment by jasimp** [comment] 2021-08-17 09:33
A new user get access to the system during the admin approval process once they click on forget password button and reset password

**Comment by deds** [comment] 2021-08-17 13:48
@jasimp try PR #46 if it solves your issue.  It doesn't need a core patch.

**Comment by jasimp** [comment] 2021-08-22 11:25
Dear Deds
So I need to patch the  below data on 2 files right?
i already did a core patch form [here :](https://github.com/hrimhari/moodle-auth_emailadmin/files/6613414/moodle-MDL-70381-patches.zip) 
is thins changed included in this patch?

![image](https://user-images.githubusercontent.com/7235269/130353232-26d0d3c0-9f39-4db1-b697-4e2ae5b6d8ce.png)


![image](https://user-images.githubusercontent.com/7235269/130353265-21334c49-0b80-4e05-8998-c921494f3414.png)

**Comment by jasimp** [comment] 2021-08-22 12:15
> I proposed a fix upstream. Please vote/comment on https://tracker.moodle.org/browse/MDL-70381

This is not opening? is this deleted?

**Comment by hrimhari** [comment] 2021-08-22 14:37
No. Assuming you created an account, I believe it's visibility may be limited because it's marked as security.
-------- Original message --------From: jasimp ***@***.***> Date: 2021-08-22  08:16  (GMT-05:00) To: hrimhari/moodle-auth_emailadmin ***@***.***> Cc: Felipe C ***@***.***>, Assign ***@***.***> Subject: Re: [hrimhari/moodle-auth_emailadmin] User can login without admin's intervention (using Re-send confirmation button) (#45) 

I proposed a fix upstream. Please vote/comment on https://tracker.moodle.org/browse/MDL-70381

This is not opening? is this deleted?

**Closed** 2021-10-01 00:43 UTC
Labels: moodle-bug
