### ISSUE TITLE
internal server error 500

### ISSUE THREAD

**Issue by fredhunterccc** [hrimhari/moodle-auth_emailadmin#12] opened 2016-12-09 14:04 UTC
I'm attempting to use this plugin on a moodle test site. whenever I attempt to sign up with a dummy account, the page errors with 'internal server error 500'. this corresponds to a an error in the logs stating:

'Failed to send an email from the user with id '5' to the user with id '2' due to the following error: "SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting'

I've gone into the Messaging outputs and added some SMTP info in, and updata the php.ini file on the host server as well, but no combination of things that I try will work.

**Comment by hrimhari** [comment] 2016-12-10 02:06
Hi fred,

Thanks for reporting this issue.

I see that you're on the right track to diagnose your SMTP issues.

Since I don't see any logging information attached to the issue, I can only suggest from what I've heard from other users.

Error 500 like that can be caused by an install error or misconfiguration of the language file. 

I've seen two such cases:
- When copying the files, they were not copied in their entirety for some reason: file corrupted.
- The Moodle is installed in a language other than English, which requires the creation of a copy of the plug-in language file to the language used.

Please provide the last few errors from your error_log after provoking the Error 500 so I can help you better. If no error is logged, you can try to increase verbosity under: 

Site administration -> Development -> Debugging.

Best regards,
Felipe

**Comment by fredhunterccc** [comment] 2016-12-12 09:14
Hi Felipe,

I’ve set the debugging to report back on all events and have recreated the incident. The only log that appears is:

[cid:image001.jpg@01D25458.2085A390]
I was testing the self registration on chrome. I’ll try a different browser and see what happens.

Fred

Fred Hunter
Systems Improvement Officer
ICT Strategy, Systems & Development
Resources Directorate, Coventry City Council

**Comment by fredhunterccc** [comment] 2016-12-12 14:26
Hi Felipe,

I’ve tried it in Internet explorer 11 but am still getting the error. How should I go about resolving the points you mentioned on my instance? I’m not a developer or a Sysadmin so I might need a bit more coaching.

Fred

Fred Hunter
Systems Improvement Officer
ICT Strategy, Systems & Development
Resources Directorate, Coventry City Council

From: Hunter, Fred
Sent: 12 December 2016 09:14
To: 'hrimhari/moodle-auth_emailadmin'
Subject: RE: [hrimhari/moodle-auth_emailadmin] internal server error 500 (#12)

Hi Felipe,

I’ve set the debugging to report back on all events and have recreated the incident. The only log that appears is:

[cid:image001.jpg@01D25483.B3C02A10]
I was testing the self registration on chrome. I’ll try a different browser and see what happens.

Fred

Fred Hunter
Systems Improvement Officer
ICT Strategy, Systems & Development
Resources Directorate, Coventry City Council

**Comment by hrimhari** [comment] 2016-12-12 16:38
Hi Fred,

I can't see your screenshot. I think that you have to add it on github. If you can't do that, please send it directly to my email, felipe AT carassonet DOT org.

Thank you,
Felipe

**Comment by fredhunterccc** [comment] 2016-12-13 15:29
![moodle logs 13122016](https://cloud.githubusercontent.com/assets/24453298/21146137/8f41824c-c148-11e6-8462-5cf52863a4ba.PNG)
Hi Felipe, this is the only log which appears when I attempt to self register as a new user. Like I said, the ID gets created and the approval email sends, but the browser I use to self-register shows an internal server error, code 500. you mentioned before the following possibilities:


  *   When copying the files, they were not copied in their entirety for some reason: file corrupted.
  *   The Moodle is installed in a language other than English, which requires the creation of a copy of the plug-in language file to the language used.

how do I go about recitfying these?

**Comment by fredhunterccc** [comment] 2016-12-13 15:56
I've got another question. I've aded a new user profile field to capture the user's establilshment (to identify which school they belong to) when I go to customise the email to the administator in the language strings, I'm trying to add the place holder in using {$a->establishment} but this doesn't show the relevant info, it just shows up the unresolved placeholder on the resultant email. This is less important, but useful to get working. If I can find out what the field is recorded as, then I can correct the placeholder. Any help you can provide with this additional query would be great.

**Comment by hrimhari** [comment] 2016-12-19 15:37
Hi Fred,

Your screen shot shows the user within the user list, but I'd need to see logs from your webserver showing the cause of the 500 error you're getting. You'd find these in a file called error.log or error_log.

As for your question, I presume you're talking about Profile Custom Fields, which get grouped within ${a->customfields}. There's no way to get one custom field by itself.

Best regards,
Felipe

**Comment by fredhunterccc** [comment] 2016-12-20 10:21
Hi Felipe,

The error logs I provided before were from within the Moodle site. I’ve searched the host computer for both error.log and error_log would it be under a different name?. For what its worth, this is a Windows Server 2012 R2 VM in my company’s Azure cloud. Also, it’s worth mentioning that if I revert back to the native email based self-registration that is built in to Moodle I don’t get the internal 500 error. Does the signup.php code need to be modified somehow to call a different confirmation/redirection procedure? I haven’t found any events in the Windows logs that correspond to the Internal 500 errors.



Fred

Fred Hunter
Systems Improvement Officer
ICT Strategy, Systems & Development
Resources Directorate, Coventry City Council

**Comment by fredhunterccc** [comment] 2016-12-22 14:36
Hi Felipe, 

I've solved the issue now. The host server had two versions of PHP running. Once I removed them both and upgraded to PHP 7, the internal 500 error no longer occurred.

The remaining query is that I can't get the email to show a custom field I've created on the user database. I have a feeling I just need to enter something into the PHP code to pass the data, but don't know how.

Thanks, 
Fred

**Comment by hrimhari** [comment] 2017-02-24 05:11
Hi Fred,

Since you solved your 500 error, I'm closing this issue.

All custom fields are dumped together with the magic variable {$a->customfields}. Check the default language file as it includes examples for the magic variables you can use.

Best regards,
Felipe

**Closed by hrimhari** 2017-02-24 05:11 UTC

**Comment by fredhunterccc** [comment] 2017-02-27 08:49
Hi Felipe,

Thanks for the follow up, I had forgotten to get back to you before. Thank you also for the note on custom fields.

Fred Hunter
Systems Improvement Officer

Corporate Users: Log your incident or service request on MyServiceDesk – no need to email or ring us

Do you have a “how do I…” IT related question? Take a look at our Ask About IT community forum
